### ISSUE TITLE
"add_to_cart" Event Fired When Updating Cart

### ISSUE THREAD

**Issue by Emmazingness** [ololabs/olo-serve-gtm-templates#20]
I have the Olo Serve tag and template implemented as instructed. 
![image](https://user-images.githubusercontent.com/108940598/188889016-d3474dd3-912d-4103-a19b-2f6ba5d2488f.png)

My GTM trigger is also set up as instructed in the ReadMe.
![image](https://user-images.githubusercontent.com/108940598/188889201-80aa8152-1e38-4385-a80f-4949ccb2d875.png)

During QA, I performed these steps and received the following results in my data layer:

- First add 2 of the same item to the cart.

![image](https://user-images.githubusercontent.com/108940598/188889760-e0ccabd9-b354-40de-a781-f904e2b70cfa.png)

 - "add_to_cart" event pushes as expected.
![image](https://user-images.githubusercontent.com/108940598/188889884-099dd0fc-d180-4509-b0be-afcf67900fe1.png)

 - Click on the item in the cart to go to the edit screen where I reduce quantity to 1.
![image](https://user-images.githubusercontent.com/108940598/188890117-ec174176-8e80-4162-9aa9-60f5e6298612.png)

 - I click "Update Cart" and the data layer shows an "add_to_cart" event instead of "remove_from_cart".
![image](https://user-images.githubusercontent.com/108940598/188890164-4aadb4df-a7ea-4549-97e3-2b93d142557d.png)

 - Go back to the edit screen and change the spice level of the dish.
![image](https://user-images.githubusercontent.com/108940598/188890200-0070f46e-7077-4487-b147-b70bf638f7d6.png)

 - Clicking "Update Cart" triggers an "add_to_cart" event instead of "update_item".
![image](https://user-images.githubusercontent.com/108940598/188890237-94fac54f-6ce5-4899-b1bb-39b2128c1d82.png)

 - Go back to the edit screen and change quantity from 1 to 2.
![image](https://user-images.githubusercontent.com/108940598/188890280-90de496e-a9db-4373-b394-5d527e74db26.png)

 - Clicking "Update Cart" sends an "add_to_cart" event that says I added 2 more items even though I only added 1.
![image](https://user-images.githubusercontent.com/108940598/188890323-034fa035-0237-451f-af0c-19b1e63fbec9.png)

Is this because both the "Add to Cart" and "Update Cart" buttons both have the same data-test-button and data-serve-element CSS selectors? As you can imagine, it messes up the sales funnel rather severely to have 3 items add to cart, 1 item remove from cart, and 1 item updated to instead report as 6 items added to cart.

**Comment by danlash** [comment]
Hello @Emmazingness . Thank you for the detailed question. I have tested this locally and see what you're seeing. I have created a bug on our internal system which will follow through our normal prioritization and scheduling process. I will write a note on there to update this Github Issue when that fix is released.

One thing I wanted to mention is that there is no update event, only add and remove.

**Comment by Emmazingness** [comment]
Yes I know there isn't a specific update event, but I didn't know what else to call it in the meantime. Thanks so much for the update, @danlash!

**Comment by kevinreedolo** [comment]
Hey @Emmazingness we have fixed this issue as of 2022-11-14T22:04Z now such that:
- on update, if quantity is decreased, then fire `remove_from_cart` with quantity that was removed (before we would wrongly fire `add_to_cart`)
- on update, if quantity is increased, then fire `add_to_cart` with quantity that was added (before we would wrongly fire `add_to_cart` with total quantity after update)
- on quick add (the `+` button), fire `add_to_cart`, but with quantity of 1 (before we would wrongly fire `add_to_cart` with total quantity after update)

Let me know if you have any further questions 👍
