### ISSUE TITLE
Invalid File Format for Container Import File

### ISSUE THREAD

**Issue by chrismccreery** [ololabs/olo-serve-gtm-templates#24]
Invalid File Format for container import.

<img width="857" alt="Screenshot 2023-12-01 at 9 52 39 am" src="https://github.com/ololabs/olo-serve-gtm-templates/assets/1922923/8ca0b726-8dd3-47f8-83a1-6c93b39b9df5">

**Comment by LauraViator** [comment]
I am also having the same issue. Can someone help?

**Comment by chrismccreery** [comment]
The format of the container is for the old GA4 config tag which no longer
exists.

I think I’ve sorted out the error but haven’t had a chance to test the
ecommerce events that it’s supposed to capture.

**Comment by chrismccreery** [comment]
You can try this modified one. There is no error on the import but I haven't had a chance to test if the tags/triggers/variables all actually work.

[olo-gtm.json](https://github.com/ololabs/olo-serve-gtm-templates/files/13552261/olo-gtm.json)

**Comment by carlosvargasolo** [comment]
Thanks @chrismccreery, we applied the changes to our files.

**Comment by carlosvargasolo** [comment]
Thanks @chrismccreery we applied the changes to our file.
