### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [ololabs/olo-serve-gtm-templates#5]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation link [https://github.com/ololabs/olo-serve-gtm-templates/README.md](https://github.com/ololabs/olo-serve-gtm-templates/README.md
![Screenshot 2020-12-17 at 1 19 11 PM](https://user-images.githubusercontent.com/53495700/102545157-bd34d780-406a-11eb-9c58-b07a5f52c73b.png)
) provided in the manifest file is not valid. It shows "Not found" error. Please provide a valid URL.

**Comment by drewloomer** [comment]
@praveena-pappu This issue has been addressed in https://github.com/ololabs/olo-serve-gtm-templates/pull/6.

**Comment by drewloomer** [comment]
Looks like the template was approved, so I'm going to close this!

**Comment by drewloomer** [comment]
@praveena-pappu how do we get new versions of this template published to the Tag Manager Gallery? We have had several releases but the Tag Manager Gallery still reflects the latest as being January. I'm not sure who else to reach out to for help.
